# Generated by Django 2.1.4 on 2018-12-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181206_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lastteacher',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
