# Generated by Django 2.1.4 on 2018-12-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_lastteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='timezone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='timeoffset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
