# Generated by Django 2.1.3 on 2018-11-29 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateField(default='2017-11-11')),
                ('hour', models.CharField(choices=[('08', '08'), ('09', '09'), ('10', '10'), ('12', '12'), ('16', '16')], default='14', max_length=2)),
                ('minute', models.CharField(choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], default='00', max_length=2)),
            ],
        ),
    ]
