# Generated by Django 2.1.4 on 2018-12-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='periods',
            field=models.TextField(),
        ),
    ]
