# Generated by Django 2.1.4 on 2018-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_auto_20181205_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
