# Generated by Django 2.1.4 on 2018-12-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_auto_20181206_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'hour']},
        ),
    ]
