# Generated by Django 2.1.4 on 2018-12-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_auto_20181206_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='hour',
            field=models.IntegerField(default=10),
        ),
    ]
