# Generated by Django 2.1.4 on 2019-01-09 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0010_auto_20181229_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot3',
            name='kydatetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
