# Generated by Django 2.1.4 on 2019-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0011_slot3_kydatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot3',
            name='kydatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
