# Generated by Django 2.1.4 on 2019-01-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0012_auto_20190109_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot3',
            name='kydatetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
