# Generated by Django 2.1.5 on 2019-01-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0014_teacher_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot3',
            name='kytime',
            field=models.FloatField(),
        ),
    ]
