# Generated by Django 2.1.5 on 2019-01-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0015_auto_20190124_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='author',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='hour',
            field=models.FloatField(default=10.0),
        ),
    ]
