# Generated by Django 2.2.1 on 2019-05-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0016_auto_20190124_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
